# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
np.random.rand(3,3,3)

array([[[0.52913971, 0.74465149, 0.23345253],
        [0.86816563, 0.99969351, 0.84176502],
        [0.17253802, 0.89288878, 0.90372269]],

       [[0.8919467 , 0.26680519, 0.05236742],
        [0.41099347, 0.63039903, 0.21439586],
        [0.83441172, 0.70223021, 0.98711594]],

       [[0.21195609, 0.37935183, 0.32926882],
        [0.11046982, 0.41429664, 0.7606412 ],
        [0.8219832 , 0.29292924, 0.71617538]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
a = np.diag(1+np.arange(4),k=-1)

print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
b = np.zeros((8,8),dtype=int)

b[1::2,::2] = 1

b[::2,1::2] = 1

print(b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
c = np.random.random((5,5))
cmax, cmin = c.max(), c.min()
c = (c - cmin)/(cmax - cmin)
print(c)

[[0.39032321 0.24424794 0.97821741 0.17656861 0.        ]
 [0.11803771 0.11293514 0.89851483 0.21607241 0.73164555]
 [0.24908163 0.59915184 0.10167466 0.8705845  0.15977262]
 [1.         0.60222659 0.47823006 0.43961777 0.22095663]
 [0.2118242  0.679212   0.78588986 0.90012511 0.74498183]]


# 5.  How to find common values between two arrays?

In [5]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 3 5 8]


# 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

# 7. Consider two random array A and B, check if they are equal

In [10]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [12]:
k = np.random.random(10)
k[k.argmax()] = 0
print(k)

[0.34028429 0.73198264 0.37556717 0.13490847 0.32048485 0.53787199
 0.5331278  0.         0.81658468 0.41755471]


# 9. How to print all the values of an array?

In [30]:
import numpy as np
import sys
nums = np.arange(7)
np.set_printoptions(threshold=sys.maxsize)
print(nums)

[0 1 2 3 4 5 6]


# 10.Subtract the mean of each row of a matrix

In [17]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)

[[-0.01190062 -0.26612345 -0.35454432  0.08426706  0.26970188 -0.43658589
   0.07836141  0.16031041  0.21119778  0.26531573]
 [-0.22883017  0.44803315  0.13239269  0.11861192  0.16178212 -0.01433357
  -0.41761979 -0.03101923  0.11328719 -0.2823043 ]
 [ 0.44048905 -0.1387952  -0.42233995 -0.01858851 -0.01273895  0.0154626
   0.13012763 -0.20248629  0.46939067 -0.26052104]
 [-0.09812671  0.25964033 -0.09228452 -0.3960401  -0.15924158  0.08124516
   0.35768209 -0.45628227  0.41497004  0.08843756]
 [ 0.18514641  0.12715437 -0.41781772  0.26303957  0.14944384 -0.35845655
  -0.16179718  0.3960328  -0.32848671  0.14574116]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [18]:
Z = np.ones(10)

I = np.random.randint(0,len(Z),20)

Z += np.bincount(I, minlength=len(Z))

print(Z)

[6. 5. 2. 5. 2. 2. 2. 1. 2. 3.]


In [19]:
np.add.at(Z, I, 1)

print(Z)

[11.  9.  3.  9.  3.  3.  3.  1.  3.  5.]


# 12.How to get the diagonal of a dot product?

In [20]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.einsum("ij,ji->i", A, B)

array([2.01328201, 1.20768566, 2.14472976, 0.64007583, 1.50664197])

# 13.How to find the most frequent value in an array?

In [22]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


# 14.How to get the n largest values of an array

In [25]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [26]:
Z = np.array([("Hello", 2.5, 3),
("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
names='col1, col2, col3',
formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
